name: Autodoc-workflow-artifacts

on:
  workflow_run:
    workflows:
      - Integration-test
    types:
      - completed

jobs:        
  autoupdate-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: dineshsonachalam/Autodoc-workflow-artifacts@v2

        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Autodoc workflow artifacts
            branch: ${{ github.head_ref }}
            file_pattern: README.md