name: markdown-autodocs

on:
  workflow_run:
    workflows:
      - integration-tests
    types:
      - completed

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.2