name: Docker

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  deploy-to-pypi:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Build python package and deploy to PYPI
          run: |
            pip3 install -r requirements-dev.txt
            sh deploy.sh

