name: Docker

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  deploy-to-pypi:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install package dependencies
          run: pip3 install -r requirements-dev.txt

        - name: Build python package and deploy to PYPI
          run: |
            rm -rf build dist *.egg-info
            python3 setup.py sdist bdist_wheel
            twine upload --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --skip-existing dist/*